# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: cuQIT Lab
email: connor.kupchak@carleton.ca
description: > # this means to ignore newlines until "baseurl:"
  The official site of the Carleton University Quantum Information Technology Lab (cuQIT)

#repository               : "ckupchak.github.io/cuQIT/"
baseurl: "https://doe.carleton.ca/~connorkupchak"
url: ""

include:
  - _pages

sass:
  sass_dir: _sass

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
